#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    networking $local_fs
# Required-Stop:     $local_fs
# Should-Start:      ifupdown
# Should-Stop:       ifupdown
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Controls the firewall
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

[ -x /sbin/iptables-restore ] || exit 0

. /lib/lsb/init-functions

RULESET="/etc/firewall/rules.iptables"
EMPTYSET="/etc/firewall/empty.iptables"

case "$1" in
start)
  log_action_begin_msg "Enabling the firewall"
  if /sbin/iptables-restore < $RULESET; then
      log_action_end_msg $?
  else
      log_action_end_msg $?
  fi
  ;;

stop)
  log_action_begin_msg "Disabling the firewall"
  if /sbin/iptables-restore < $EMPTYSET; then
      log_action_end_msg $?
  else
      log_action_end_msg $?
  fi
  ;;

reload|restart)
  log_action_begin_msg "Reloading the firewall"
  if /sbin/iptables-restore < $RULESET; then
      log_action_end_msg $?
  else
      log_action_end_msg $?
  fi
  ;;

status)
  /sbin/iptables -L -n -v
  /sbin/iptables -L -t nat -n -v
  /sbin/iptables -L -t mangle -n -v
  ;;

*)
  echo "Usage: /etc/init.d/firewall {start|stop}"
  exit 1
  ;;
esac

exit 0
