#!/bin/bash
# afw   iptables firewall init script
# chkconfig: 2345 65 90
# description: iptables firewall script
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    networking $local_fs
# Required-Stop:     $local_fs
# Should-Start:      ifupdown
# Should-Stop:       ifupdown
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Controls the firewall
### END INIT INFO

[ -x /sbin/iptables-restore ] || exit 0

RULESET="/etc/firewall/rules.iptables"
EMPTYSET="/etc/firewall/empty.iptables"

case "$1" in
  start|reload|restart)
    echo -n "Enabling the firewall: "
    if /sbin/iptables-restore < $RULESET; then
      echo "OK"
    else
      echo "Failed ! $?"
    fi
    ;;

  stop)
    echo -n "Disabling the firewall:"
    if /sbin/iptables-restore < $EMPTYSET; then
      echo "OK"
    else
      echo "Failed ! $?"
    fi
    ;;

  status)
    /sbin/iptables -L -n -v
    /sbin/iptables -L -t nat -n -v
    /sbin/iptables -L -t mangle -n -v
    ;;

  *)
    echo "Usage: /etc/init.d/firewall {start|stop|reload|restart|status}"
    exit 1
    ;;
esac

exit 0
